version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "5001:5001"
    env_file:
      - ./auth-service/.env
    networks:
      - backend

  platform-service:
    build: ./platform-service
    ports:
      - "5002:5002"
    env_file:
      - ./platform-service/.env
    networks:
      - backend

  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "8520:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - platform-service
    networks:
      - backend

networks:
  backend:
    driver: bridge
