services:
  auth-service:
    build: ./auth-service
    ports:
      - "5001:5001"
    env_file:
      - ./auth-service/.env
    networks:
      - backend

  platform-service:
    build: ./platform-service
    ports:
      - "5002:5002"
    env_file:
      - ./platform-service/.env
    networks:
      - backend

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8515:80"
    depends_on:
      - auth-service
      - platform-service
    networks:
      - backend

networks:
  backend:
    driver: bridge
