version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "5001:5001"
    env_file:
      - ./auth-service/.env

  platform-service:
    build: ./platform-service
    ports:
      - "5002:5002"
    env_file:
      - ./platform-service/.env

