services:
  auth-service:
    image: ajxdoc/auth-service:latest
    ports:
      - "5001:5001"
    env_file:
      - ./auth-service/.env
    networks:
      - backend

  platform-service:
    image: ajxdoc/platform-service:latest
    ports:
      - "5002:5002"
    env_file:
      - ./platform-service/.env
    networks:
      - backend

  api-gateway:
    image: ajxdoc/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8515:80"
    depends_on:
      - auth-service
      - platform-service
    networks:
      - backend

networks:
  backend:
    driver: bridge
