name: Deploy to Docker Hub and Oracle VPS

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Debug Secrets
              run: |
                  echo "DOCKER_USERNAME length: ${#DOCKER_USERNAME}"
                  echo "DOCKER_PASSWORD length: ${#DOCKER_PASSWORD}"
              env:
                  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Docker image
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/proact_backend:latest .
                  docker push ${{ secrets.DOCKER_USERNAME }}/proact_backend:latest

            - name: Deploy via SSH to server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      cd ${{ secrets.PROJECT_PATH }}
                      docker-compose down
                      docker pull ${{ secrets.DOCKER_USERNAME }}/proact_backend:latest
                      docker-compose up -d
                      docker image prune -f
