name: Deploy to Docker Hub

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Docker image
              run: |
                  # Build the Docker image
                  docker build -t ajxdoc/proact_backend:latest .
                  # Push the Docker image to Docker Hub
                  docker push ajxdoc/proact_backend:latest

            - name: Deploy via SSH to server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      cd ${{ secrets.PROJECT_PATH }}

                      # Stop any running containers (if necessary)
                      docker-compose down

                      # Pull the latest image from Docker Hub
                      docker pull your-dockerhub-username/your-image-name:latest

                      # Rebuild and start the service with the new image
                      docker-compose up -d

                      # Optionally prune old images
                      docker image prune -f
